# Generated by Django 5.0.4 on 2024-05-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
