# Generated by Django 5.0.4 on 2024-05-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_category_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tag',
        ),
    ]
