# Generated by Django 5.0.4 on 2024-05-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0009_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
