# Generated by Django 5.0.4 on 2024-05-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0011_alter_blogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(default='draft', max_length=50),
        ),
        migrations.AddField(
            model_name='tag',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
