# Generated by Django 5.0.4 on 2024-05-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0012_blogpost_status_tag_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
