# Generated by Django 5.0.4 on 2024-05-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0013_alter_blogpost_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='image',
            new_name='blog_images',
        ),
    ]
