# Generated by Django 5.0.4 on 2024-05-10 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_view', '0001_initial'),
        ('sign', '0013_alter_blogpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlogs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.user'),
        ),
    ]
