# Generated by Django 5.0.4 on 2024-05-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_view', '0002_alter_adminlogs_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlogs',
            name='user',
        ),
    ]
